# Generated by Django 5.1.1 on 2024-11-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0002_gamesession_case_file_cards_gamesession_current_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='location_state',
            field=models.JSONField(default=None, null=True),
        ),
    ]
